import type { LearningResource } from "./types";

/*
 * Courses, certificates and reading that close common gaps. Each link, name,
 * effort and cost was checked against the provider's own page on 2026-10-01;
 * where a provider doesn't state a price, the cost says so rather than
 * guessing. Recheck before relying on a price.
 */

export const RESOURCES_CHECKED_ON = "2026-10-01";

export const RESOURCES: LearningResource[] = [
  {
    key: "trailhead-crm",
    title: "Salesforce CRM (Trailhead module)",
    provider: "Salesforce Trailhead",
    url: "https://trailhead.salesforce.com/content/learn/modules/lex_implementation_basics",
    cost: "Free",
    effort: "About 50 minutes",
    paths: ["customer_success", "account_management", "implementation"],
    covers: ["salesforce", "crm"],
    certificate: false,
    why: "The fastest way to stop \"Salesforce\" from being a gap: navigation, records and daily use.",
  },
  {
    key: "trailhead-admin-beginner",
    title: "Admin Beginner (Trailhead trail)",
    provider: "Salesforce Trailhead",
    url: "https://trailhead.salesforce.com/content/learn/trails/force_com_admin_beginner",
    cost: "Free",
    effort: "About 7 hours",
    paths: ["implementation", "customer_success"],
    covers: ["salesforce", "crm", "configuration", "dashboard", "data-migration"],
    certificate: false,
    why: "Teaches configuration, data and reports, which is the core of implementation work, on the most common platform.",
  },
  {
    key: "hubspot-service-hub",
    title: "Service Hub Software Certification Course",
    provider: "HubSpot Academy",
    url: "https://academy.hubspot.com/courses/hubspot-service-software",
    cost: "Free course; the certification's practical exercises need a Pro or Enterprise HubSpot subscription",
    effort: "About 2.5 hours",
    paths: ["customer_success", "implementation"],
    covers: ["hubspot", "support-desk", "knowledge-base", "csat", "nps", "crm"],
    certificate: true,
    why: "Hands-on with a real service platform: help desk, knowledge base, feedback surveys and reporting.",
  },
  {
    key: "hubspot-support",
    title: "Delivering Exceptional Customer Support",
    provider: "HubSpot Academy",
    url: "https://academy.hubspot.com/courses/delivering-exceptional-customer-support",
    cost: "Free",
    effort: "About 1 hour",
    paths: ["customer_success"],
    covers: ["ticket", "sla", "support-tiers", "csat", "escalation"],
    certificate: false,
    why: "Short grounding in how support works: troubleshooting, SLAs and support metrics. CS works next to it every day.",
  },
  {
    key: "gainsight-csm",
    title: "Customer Success Manager certification (Pulse+)",
    provider: "Gainsight",
    url: "https://education.gainsight.com/page/customer-success",
    cost: "Paid; confirm the current price on the site",
    effort: "",
    paths: ["customer_success"],
    covers: ["cs-platform", "health-score", "success-plan", "qbr", "churn", "nrr", "grr", "playbook", "segmentation"],
    certificate: true,
    why: "A recognized CS credential from the company behind the most common CS platform. Worth it once you're sure about CS.",
  },
  {
    key: "atlassian-jira",
    title: "Jira fundamentals (Atlassian learning catalog)",
    provider: "Atlassian",
    url: "https://community.atlassian.com/learning/catalog?product=Jira",
    cost: "Free",
    effort: "About 1.5 hours",
    paths: ["implementation"],
    covers: ["jira", "agile", "dependency", "ticket"],
    certificate: false,
    why: "Jira shows up in most implementation postings. The free fundamentals courses end with a badge.",
  },
  {
    key: "google-pm",
    title: "Google Project Management Professional Certificate",
    provider: "Google on Coursera",
    url: "https://www.coursera.org/professional-certificates/google-project-management",
    cost: "Coursera subscription: $49/month in the US after a 7-day free trial",
    effort: "7 courses; about 6 months at 10 hours a week",
    paths: ["implementation", "employer_wellbeing"],
    covers: ["project-plan", "milestone", "dependency", "raci", "raid-log", "agile", "scope-creep", "change-management", "status-report", "kickoff", "pm-tools"],
    certificate: true,
    why: "Gives the project vocabulary implementation interviews use, with a credential recruiters recognize.",
  },
  {
    key: "rocketlane-academy",
    title: "Rocketlane Academy",
    provider: "Rocketlane",
    url: "https://academy.rocketlane.com/",
    cost: "Free with registration",
    effort: "",
    paths: ["implementation"],
    covers: ["pm-tools", "onboarding", "project-plan"],
    certificate: false,
    why: "Product training for a purpose-built onboarding tool, useful for seeing how implementation teams structure customer projects.",
  },
  {
    key: "wellness-alliance-wws",
    title: "Worksite Wellness Specialist Certificate",
    provider: "Wellness Alliance (WELCOA + National Wellness Institute)",
    url: "https://www.wellnessalliance.org/d/course-wa/worksite-wellness-specialist",
    cost: "2026: $995 members / $1,195 non-members (early-registration discounts available)",
    effort: "6 weeks: 8 self-paced modules with a cohort, plus a final exam",
    paths: ["employer_wellbeing"],
    covers: ["employer-wellbeing", "population-health", "engagement-rate", "comms-plan", "voi", "roi", "total-rewards"],
    certificate: true,
    why: "The established worksite-wellness credential. It frames your coaching experience in the employer's language.",
  },
  {
    key: "kff-ehbs",
    title: "2025 Employer Health Benefits Survey",
    provider: "KFF",
    url: "https://www.kff.org/health-costs/report/2025-employer-health-benefits-survey/",
    cost: "Free",
    effort: "",
    paths: ["employer_wellbeing"],
    covers: ["self-insured", "carrier", "total-rewards", "hsa-fsa", "incentives", "biometric-screening", "tpa"],
    certificate: false,
    why: "The standard annual source on what employers spend and offer. Quoting it shows you understand the buyer.",
  },
  {
    key: "hero-scorecard",
    title: "HERO Health and Well-being Best Practices Scorecard",
    provider: "Health Enhancement Research Organization (HERO)",
    url: "https://hero-health.org/hero-scorecard/",
    cost: "The page doesn't state a price; see site",
    effort: "",
    paths: ["employer_wellbeing"],
    covers: ["population-health", "employer-wellbeing", "sdoh", "mental-health-benefits"],
    certificate: false,
    why: "Shows what employers are assessed against as best practice: useful framing for needs assessments and renewals.",
  },
];
